export const shoplists = [
  {
    shopId: "1",
    shopImage: "Shop1.jpeg",
    shopDesc: `브로샵 청평 대리점 D3스키, /\d 에이드전제품 중고원스키전문 /n광고,흥보,대리판매DM주세요 /n장비선택문의주세요 /n카톡 34ㄱㅇㄴㄹ /n📞 010 555 8733`,
    shopType: "water",
    shopSubType: "scuba",
    shopTitle: "[양양]노블레스다이빙 센터",
    shopPrice: "80,000₩",
    shopStar: "5",
    shopDiscount: "20%",
    shopComment: "(30)",
  },
  {
    shopId: "2",
    shopImage: "Shop2.jpeg",
    shopDesc: "Water",
    shopType: "water",
    shopSubType: "scuba",
    shopTitle: "[제주]포세이돈 다이빙샵",
    shopPrice: "100,000₩",
    shopStar: "4.9",
    shopDiscount: "",
    shopComment: "(25)",
  },
  {
    shopId: "3",
    shopImage: "Shop3.jpeg",
    shopDesc: "Water",
    shopType: "water",
    shopSubType: "scuba",
    shopTitle: "[제주]다이브인",
    shopPrice: "120,000₩",
    shopStar: "4.5",
    shopDiscount: "",
    shopComment: "(5)",
  },
  {
    shopId: "4",
    shopImage: "Shop4.jpeg",
    shopDesc: "Water",
    shopType: "water",
    shopSubType: "scuba",
    shopTitle: "[세부] 망고 다이빙 리조트",
    shopPrice: "3,000PHP",
    shopStar: "4.9",
    shopDiscount: "20%",
    shopComment: "(124)",
  },
  {
    shopId: "5",
    shopImage: "Shop5.png",
    shopDesc: "Water",
    shopType: "water",
    shopSubType: "scuba",
    shopTitle: "[고성] 모두 다이빙 리조트",
    shopPrice: "100,000₩",
    shopStar: "5.0",
    shopDiscount: "",
    shopComment: "(3)",
  },
  {
    shopId: "6",
    shopImage: "Shop6.png",
    shopDesc: "Water",
    shopType: "water",
    shopSubType: "scuba",
    shopTitle: "[양양] 인투 다이빙샵",
    shopPrice: "90,000₩",
    shopStar: "4.8",
    shopDiscount: "10%",
    shopComment: "(23)",
  },
];
